defaults: &defaults
  docker:
    - image: petrpliska/shopsys-buildpack:0.1.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
  working_directory: ~/source

login-to-dockerhub: &login-to-dockerhub
  name: Login to Docker hub
  command: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

create-google-service-account-file: &create-google-service-account-file
  name: Create google service account file
  command: echo "$GOOGLE_SERVICE_ACCOUNT">/etc/google-service-account.json

version: 2
jobs:
  deploy-to-k8s:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build docker image
          command: docker image build --build-arg version=$CIRCLE_BRANCH-$CIRCLE_SHA1 --tag $DOCKER_REPOSITORY:$CIRCLE_BRANCH-$CIRCLE_SHA1 --tag $DOCKER_REPOSITORY:latest .
      - run:
          <<: *login-to-dockerhub
      - run:
          name: Push docker image into registry
          command: docker image push $DOCKER_REPOSITORY:$CIRCLE_BRANCH-$CIRCLE_SHA1
      - run:
          <<: *create-google-service-account-file
      - run:
          name: Deploy to k8s
          command: echo "Deploy yeaaaah"

workflows:
  version: 2
  deployment:
    jobs:
      - deploy-to-k8s:
          filters:
            tags:
              ignore: /.*/